// ============================================================
// Mock data fallback for development / offline mode
// Set USE_MOCK_DATA=true in .env.local to use this instead of live APIs
// ============================================================

import type { EditorialArticle, PredictionMarket } from "@/types";

export const MOCK_ARTICLES: EditorialArticle[] = [
  {
    id: "guardian-mock-1",
    source: "guardian",
    title: "Global AI regulation talks intensify as leaders gather in Geneva",
    summary: "World leaders and technology executives convene in Geneva for emergency talks on artificial intelligence governance, amid growing concerns about AI safety and geopolitical competition.",
    url: "https://www.theguardian.com/technology/2024/mock-ai-regulation",
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    section: "Technology",
    extractedKeywords: ["ai", "regulation", "geneva", "governance", "safety", "geopolitical"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "guardian-mock-2",
    source: "guardian",
    title: "Federal Reserve signals potential rate cut as inflation data improves",
    summary: "The Federal Reserve has hinted at a possible interest rate reduction in coming months following better-than-expected inflation figures, boosting equity markets globally.",
    url: "https://www.theguardian.com/business/2024/mock-fed-rates",
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    section: "Business",
    extractedKeywords: ["federal reserve", "rate cut", "inflation", "interest rates", "equity", "markets"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "aljazeera-mock-1",
    source: "aljazeera",
    title: "Ceasefire negotiations in Gaza reach critical juncture",
    summary: "Mediators from Qatar and Egypt are pressing both parties to accept a framework deal as humanitarian conditions deteriorate and international pressure mounts.",
    url: "https://www.aljazeera.com/news/2024/mock-gaza-ceasefire",
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    section: "Middle East",
    extractedKeywords: ["ceasefire", "gaza", "negotiations", "humanitarian", "mediators", "qatar"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "lemonde-mock-1",
    source: "lemonde",
    title: "L'intelligence artificielle au cœur des tensions géopolitiques mondiales",
    summary: "AI competition between the United States and China is increasingly shaping global power dynamics, with European nations seeking an independent regulatory path.",
    url: "https://www.lemonde.fr/technologie/2024/mock-ia-geopolitique",
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    section: "Technologie",
    extractedKeywords: ["intelligence artificielle", "geopolitique", "chine", "etats-unis", "regulation", "europe"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "guardian-mock-3",
    source: "guardian",
    title: "Bitcoin surpasses $80,000 as institutional adoption accelerates",
    summary: "Bitcoin has crossed the $80,000 threshold for the first time as major financial institutions announce expanded cryptocurrency holdings and ETF inflows hit record levels.",
    url: "https://www.theguardian.com/technology/2024/mock-bitcoin-80k",
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    section: "Technology",
    extractedKeywords: ["bitcoin", "cryptocurrency", "institutional", "etf", "crypto", "blockchain"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "aljazeera-mock-2",
    source: "aljazeera",
    title: "Record temperatures across three continents signal climate emergency",
    summary: "Scientists warn that simultaneous heat extremes across Europe, Asia, and North America represent a new phase of climate disruption, urging immediate emissions action.",
    url: "https://www.aljazeera.com/environment/2024/mock-climate",
    publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    section: "Climate",
    extractedKeywords: ["climate", "temperature", "heat", "emissions", "global warming", "scientists"],
    matchedTopics: [],
    relevanceScore: 0,
  },
];

export const MOCK_MARKETS: PredictionMarket[] = [
  {
    id: "polymarket-mock-1",
    source: "polymarket",
    title: "Will the US Federal Reserve cut interest rates before end of 2024?",
    eventTitle: "Fed Rate Decision 2024",
    url: "https://polymarket.com/event/fed-rate-cut-2024",
    category: "Economics",
    yesPrice: 0.72,
    noPrice: 0.28,
    probabilityYes: 72,
    probabilityNo: 28,
    volume: 4_500_000,
    openInterest: 1_200_000,
    endDate: "2024-12-31",
    active: true,
    extractedKeywords: ["federal reserve", "rate cut", "interest rates", "monetary policy"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "polymarket-mock-2",
    source: "polymarket",
    title: "Will there be a ceasefire agreement in Gaza by end of Q1 2025?",
    eventTitle: "Gaza Ceasefire Agreement",
    url: "https://polymarket.com/event/gaza-ceasefire-q1-2025",
    category: "Geopolitics",
    yesPrice: 0.41,
    noPrice: 0.59,
    probabilityYes: 41,
    probabilityNo: 59,
    volume: 2_800_000,
    openInterest: 900_000,
    active: true,
    extractedKeywords: ["ceasefire", "gaza", "israel", "middle east", "peace"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "polymarket-mock-3",
    source: "polymarket",
    title: "Will Bitcoin reach $100,000 in 2024?",
    eventTitle: "Bitcoin $100k",
    url: "https://polymarket.com/event/bitcoin-100k-2024",
    category: "Crypto",
    yesPrice: 0.65,
    noPrice: 0.35,
    probabilityYes: 65,
    probabilityNo: 35,
    volume: 8_200_000,
    openInterest: 3_100_000,
    endDate: "2024-12-31",
    active: true,
    extractedKeywords: ["bitcoin", "btc", "cryptocurrency", "100k"],
    matchedTopics: [],
    relevanceScore: 0,
  },
  {
    id: "polymarket-mock-4",
    source: "polymarket",
    title: "Will global CO2 emissions peak before 2026?",
    eventTitle: "Global Emissions Peak",
    url: "https://polymarket.com/event/co2-emissions-peak-2026",
    category: "Climate",
    yesPrice: 0.38,
    noPrice: 0.62,
    probabilityYes: 38,
    probabilityNo: 62,
    volume: 1_100_000,
    openInterest: 400_000,
    active: true,
    extractedKeywords: ["co2", "emissions", "climate", "carbon", "peak"],
    matchedTopics: [],
    relevanceScore: 0,
  },
];

export function isMockMode(): boolean {
  return process.env.USE_MOCK_DATA === "true";
}
